---
title: "Joining and tidying"
author: "Marjorie Blanco"
date: "11/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Joining and tidying

```{r}
library(dplyr)

# Add a country column within the mutate: votes_processed
votes_processed <- votes %>%
  filter(vote <= 3) %>%
  mutate(year = session + 1945,
         country = countrycode(ccode, "cown", "country.name"))


# Join them together based on the "rcid" and "session" columns
votes_processed %>% inner_join(descriptions, by = c("rcid", "session"))
                               # Filter for votes related to colonialism
votes_joined %>% filter(co == TRUE)

# Load the ggplot2 package
library(ggplot2)

# Filter, then summarize by year: US_co_by_year
US_co_by_year <- (votes_joined) %>% filter(co == 1, country == 'United States') %>% group_by(year) %>% summarize(percent_yes = mean(vote ==  1))

# Graph the % of "yes" votes over time
ggplot(US_co_by_year,aes(x= year, y= percent_yes)) +
  geom_line()

# Gather the six me/nu/di/hr/co/ec columns
votes_joined %>% gather(topic, has_topic, me:ec)

# Perform gather again, then filter
votes_gathered <- votes_joined %>% gather(topic, has_topic, me:ec) %>% filter(has_topic != 0)
 

# Summarize the percentage "yes" per country-year-topic
by_country_year_topic <- votes_tidied %>% group_by(country, year, topic) %>% summarize(total = n(),
percent_yes = mean(vote == 1)) %>% ungroup()


# Plot % yes over time for the US, faceting by topic
ggplot(US_by_country_year_topic, aes(x= year, y=percent_yes)) +
geom_line() +
facet_wrap(~topic)


# Load purrr, tidyr, and broom
library(tidyr)
library(purrr)
library(broom)


# Print by_country_year_topic
by_country_year_topic

# Fit model on the by_country_year_topic dataset
country_topic_coefficients <- by_country_year_topic %>%
  nest(-country, -topic) %>%
  mutate(model = map(data, ~ lm(percent_yes ~ year, data = .)),
         tidied = map(model, tidy)) %>%
  unnest(tidied)


# Print country_topic_coefficients
country_topic_coefficients

# Create country_topic_filtered
country_topic_filtered <- country_topic_coefficients %>% 
filter(term == "year") %>% mutate(p.adjusted = p.adjust(p.value)) %>%
filter(p.adjusted < 0.05)

# Create vanuatu_by_country_year_topic
vanuatu_by_country_year_topic <- by_country_year_topic %>% filter(country == 
"Vanuatu")

# Plot of percentage "yes" over time, faceted by topic
ggplot(vanuatu_by_country_year_topic, aes(x=year, y=percent_yes), vanuatu_by_country_year_topic) +
  geom_line() +
  facet_wrap(~topic)
```

