---
title: "Introduction to Modeling"
author: "Marjorie Blanco"
date: "11/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(moderndive)
library(ggplot2)
library(dplyr)
```

# Introduction to Modeling

```{r}
glimpse(evals)

# Plot the histogram
ggplot(evals, aes(x = score)) +
  geom_histogram(binwidth = 5) +
  labs(x = "Testing score", y = "count")

# Compute summary stats
evals %>%
  summarize(mean_score = mean(score),
            median_score = median(score),
            sd_score = sd(score))

# Plot the histogram
ggplot(evals, aes(x = age)) +
  geom_histogram(binwidth = 5) +
  labs(x = "age", y = "count")

# Compute summary stats
evals %>%
  summarize(mean_age = mean(age),
            median_age = median(age),
            sd_age = sd(age))
```

```{r}
glimpse(house_prices)

# Plot the histogram
ggplot(house_prices, aes(x = price)) +
  geom_histogram()+
  labs(x = "Price", y = "count")

# Compute summary stats
house_prices %>%
  summarize(mean_price = mean(price),
            median_price = median(price),
            sd_price = sd(price))

# Add log10_size
house_prices <- house_prices %>%
  mutate(log10_price = log10(price))


# Plot the histogram
ggplot(house_prices, aes(x = price)) +
  geom_histogram() +
  labs(x = "House price", y = "count")


# Plot the histogram
ggplot(house_prices, aes(x = log10_price)) +
  geom_histogram() +
  labs(x = "House price (log10)", y = "count")


# Plot the histogram
ggplot(house_prices, aes(x = sqft_living)) +
  geom_histogram() +
  labs(x = "Size (sq.feet)", y = "count")

# Add log10_size
house_prices_2 <- house_prices %>%
  mutate(log10_size = log10(sqft_living))

# Plot the histogram
ggplot(evals, aes(x=bty_avg)) +
  geom_histogram(binwidth = 0.5) +
  labs(x = "Beauty score", y = "count")

#numerically summarize the relationship between teaching score and beauty score bty_avg using the correlation coefficient. Based on this, what can you say about the relationship between these two variables?
# Compute correlation
evals %>%
  summarize(correlation = cor(score,bty_avg))
#score and bty_avg are weakly positively associated.

house_prices %>% select(log10_price, condition) %>% glimpse()

ggplot(house_prices, aes(x=  condition, y = log10_price)) +
  geom_boxplot() +
  labs(x = "condition", y = "log 10 price")


# Compute summary stats
house_prices %>%
  group_by(condition) %>% 
  summarize(mean_price = mean(log10_price),
            median_price = median(log10_price),
            sd_price = sd(log10_price),
            n = n())

10^(5.65)


# View the structure of log10_price and waterfront
house_prices %>%
  select(log10_price, waterfront) %>%
  glimpse()

# Plot 
ggplot(house_prices, aes(x = waterfront, y = log10_price)) +
  geom_boxplot() +
  labs(x = "waterfront", y = "log10 price")
#Houses that have a view of the waterfront tend to be MUCH more expensive as evidenced by the much higher log10 prices!

# Calculate stats
house_prices %>%
  group_by(waterfront) %>%
  summarize(mean_log10_price = mean(log10_price), n = n())
  
# Prediction of price for houses with view
10^(6.12)

# Prediction of price for houses without view
10^(5.66)

#Most houses don't have a view of the waterfront (n = 21,450), but those that do (n = 163) have a MUCH higher predicted price. Look at that difference! $457,088 versus $1,318,257! In the upcoming Chapter 2 on basic regression, we'll build on such intuition and construct our first formal explanatory and predictive models using basic regression!
```

